---
title: "The Biways"
---

The British Isles, also known as the Biways, consists of England, Scotland, Ireland, Wales, Greenland, Iceland, and other smaller islands.

## Primary deity

None/agnostic

## Positives

- __Rich:__ The Biways is the financial hub of the world. The pound is the most traded and trusted currency in the world.
- __Nuclear power:__ Greenland is used for nuclear power generation to sell to the world, especially the USA.
- __Research:__ Contains many universities with leading research.


## Negatives

- __Corrupt:__ It is a great place for off shore bank accounts and laundering money. It is a haven for international fugitives, as long as they have the capital. Many of the world's elites and most dangerous live in the Biways, benefiting from interacting with each other.
- __Dangerous science:__ Dangerous scientific research is carried out in Iceland by super scientists from across the world.
- __Brain drain:__ The Biways is very attractive to experts across the world. Unfortunately this takes away specialists from countries that need them more.
